spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl

redis:
  host: 127.0.0.1
  port: 6379